blog/blog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r"^myblog/", include("myblog.urls", namespace="myblog")),
    url(r'^admin/', include(admin.site.urls)),
)

blog/myblog/urls.py
from django.conf.urls import patterns, url

from myblog import views

urlpatterns = patterns("",
                       url(r"^$", views.index, name="index"),
                       url(r"^(?P<article_id>\d+)/$", views.show_article,
                           name="show-article"),
                       url(r"^contact/$", views.contact,
                           name="contact"),
                       url(r"^(\d+/)?contact/$", views.contact,
                           name="contact"),
                       )

blog/myblog/models.py
from django.db import models
from django.utils import timezone
import datetime


class Author(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


# class Comment(models.Model):
#     comment_body = models.TextField(max_length=300, default="")

#     def __unicode__(self):
#         return self.comment_body


class Article(models.Model):
    title = models.CharField(max_length=30, default="")
    text = models.TextField(max_length=10000)
    pub_date = models.DateTimeField("date published")
    author = models.ForeignKey(Author)
    image = models.URLField(default="http://www.zahorata.com/images/uploaded_images/pic_1343_bg.jpg")
    slider_image = models.URLField(default="https://wallpapersinbox.files.wordpress.com/2011/07/natgeo1.jpg")
    rating = models.IntegerField(default=0)
    comment = models.TextField(max_length=300, default="")
    # comment = models.ForeignKey(Comment)

    def __str__(self):
        return self.title

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=5)
    was_published_recently.admin_order_field = "pub_date"
    was_published_recently.boolean = True
    was_published_recently.short_description = "Published recently?"

blog/myblog/forms.py
from django.forms import ModelForm
# from django import forms
from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        # fields = ["title", "text", "author", "pub_date", "rating", "comment"]
        fields = "__all__"

# form = ArticleForm()

blog/myblog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, HttpResponse
from myblog.models import Article
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.core.urlresolvers import reverse


def index(request):
    latest_articles = Article.objects.filter(pub_date__lte=timezone.now()
                                             ).order_by("-pub_date")[:5]
    most_rated = Article.objects.order_by("-rating")[:3]
    for article in most_rated:
        if article.text.count(".") > 1:
            current = article.text.split(".")
            article.text = current[0] + ". " + current[1]
        else:
            article.text = article.text[:30]
    context = {"latest_articles": latest_articles, "most_rated": most_rated}
    return render(request, "myblog/index.html", context)


@csrf_exempt
def show_article(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if request.method == "POST":
        if request.POST.get("id"):
            article.rating += 1
            article.save()
            print("show_article - like")
            return HttpResponse(request.POST.get("id"))
        article.comment = request.POST.get("comment")
        article.save()
        print("show_article - send comment")
        return HttpResponse(article.comment)
    print("show_article - get")
    return render(request, "myblog/show_article.html", {"article": article})


def contact(request):
    return render(request, "myblog/contact.html", {"contact": contact})

blog/myblog/templates/myblog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="google-translate-customization" content="1b6e87e57be49eb-2b4d7c8e5d8aaf01-gbf42a6299e3604b7-19"></meta>
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


    <title>David Baldacci's Blog</title>
    <link href="/static/carousel.css" rel="stylesheet">
</head>
<!-- NAVBAR
================================================== -->

<body>
    <div class="navbar-wrapper">
        <div class="container">

            <div class="navbar navbar-inverse navbar-static-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="http://davidbaldacci.com/">David Baldacci</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a href='{% url "myblog:index" %}'>Home</a>
                            </li>

                            <li><a href='{% url "myblog:contact" %}'>Contact</a>
                            </li>
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">DB's info <span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                <li><a href="http://davidbaldacci.com/about-david/">Biography</a></li>
                                <li><a href="http://davidbaldacci.com/books/books/">Books</a></li>
                                <li><a href="http://davidbaldacci.com/events/book-signings/">Author events</a></li>
                                <!-- <li class="divider"></li>
                                <li class="dropdown-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li> -->
                              </ul>
                            </li>
                        </ul>
                        {% block translate %}
                        <div id="google_translate_element">
                            <script type="text/javascript">
                            function googleTranslateElementInit() {
                                new google.translate.TranslateElement({
                                    pageLanguage: 'en',
                                    layout: google.translate.TranslateElement.InlineLayout.SIMPLE,
                                    multilanguagePage: true
                                }, 'google_translate_element');
                            }
                            </script>
                            <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
                            {% endblock translate %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Carousel
    ================================================== -->
        {% block top_news %} {% endblock top_news %}

        <!-- Marketing messaging and featurettes
    ================================================== -->
        {% block review %} {% endblock review %} {% block latest_news %} {% endblock latest_news %} {% block contact %} {% endblock contact %} {% block go_back %} {% endblock go_back %}

        <!-- <hr> -->

        <!-- FOOTER -->
        <footer>
            <p class="pull-right"><a href="#">Back to top</a>
            </p>
            <p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a>
            </p>
        </footer>

    </div>
    <!-- /.container -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <!-- Java Script -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
    <script src="/static/app.js"></script>
</body>

</html>

blog/myblog/templates/myblog/contact.html
{% extends 'myblog/base.html' %}

{% block contact %}
<div class="align-text">
    <form>
        <h3>Speaking Engagements</h3>
        <ul>
            <li>
                <p>To inquire about booking David for an event, please contact:</p>
                <p>Keppler Speakers Bureau</p>
                <p>703-516-4000</p>
            </li>
        </ul>
        <h3>Publicity</h3>
        <ul>
            <li>
                <p>To inquire about interviewing David or inviting him to do a book signing, please contact:</p>
                <p>Sonya Cheuse</p>
                <p>Grand Central Publishing</p>
                <p>Sonya.Cheuse@hbgusa.com</p>
                <p>212-364-1496</p>
            </li>
        </ul>
        <h3>Foundation</h3>
        <ul>
            <li>
                <p>For more information about the Wish You Well Foundation, please contact:</p>
                <p>Natasha Collin</p>
                <p>Executive Director</p>
                <p>Wish You Well Foundation</p>
                <p>natasha@wishyouwellfoundation.org</p>
                <p>703-476-6032</p>
            </li>
        </ul>

        <button type="button" class="btn btn-info btn-lg pull-right" id="back">Back</button>
        <br/>
    </form>
    </div>
    <br/>
    <br/>
    <hr>
{% endblock contact%}

blog/myblog/templates/myblog/index.html
{% extends 'myblog/base.html' %} {% block review %}
<div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-lg-4">
            <img class="img-circle" src="http://images.nationalgeographic.com/wpf/media-content/photos/000/824/cache/82421_990x742-cb1407340020.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
            <h2>Halo</h2>
            <p>Ich bin froh, dass besuchen Sie meiner Seite :) Ich wünsche Sie eine gute Reise haben!</p>
            <p>German</p>
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img-circle" src="http://images.nationalgeographic.com/wpf/media-live/photos/000/825/cache/perseid-meteor-shower-01_82581_990x742.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
            <h2>Hola</h2>
            <p>Me alegro de que estés visitando mi página :) Que tengas un buen viaje a través de él!</p>
            <p>Español</p>
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img-circle" src="http://images.nationalgeographic.com/wpf/media-content/photos/000/823/cache/82396_990x742-cb1407254922.jpg" alt="Generic placeholder image" style="width: 140px; height: 140px;">
            <h2>Bonjour</h2>
            <p>Je suis heureux que vous visitez ma page :) Bon voyage à travers elle!</p>
            <p>Français</p>
        </div>
        <!-- /.col-lg-4 -->
        <div class="col-lg-7">
            {% block translate.super %} {% endblock translate.super %}
        </div>
    </div>
    <!-- /.row -->
    {% endblock %}


{% block top_news %}
{% if most_rated %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
{% for article in most_rated %}
        <div class="item {% if article.id == most_rated.0.id %} active active-slide {% endif %}">

            <img src={{ article.slider_image }}>
            <div class="container">
                <div class="carousel-caption">
                    <h1>{{ article.title }}</h1>
                    <p>{{ article.text }}.</p>
                    <p><a class="btn btn-lg btn-primary" href="{% url 'myblog:show-article' article.id %}" role="button">Learn more</a>
                    </p>
                </div>
            </div>
        </div>
{% endfor %}
    </div>
    <a class="left carousel-control" role="button" data-slide="prev" id="left">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" role="button" data-slide="next" id="right">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>

    <!-- Indicators -->
    <div class="dots">
    <ul class="slider-dots">
        <li class="dot active-dot">&bull;</li>
        <li class="dot">&bull;</li>
        <li class="dot">&bull;</li>
    </ul>
    </div>
</div>
<!-- /.carousel -->
{% endif %}
{% endblock %}


{% block latest_news %}
    {% if latest_articles %}
        <hr/>
        <ul>
        <h1 class="news">Latest news</h1>
        <!-- <br/> -->
        {% for article in latest_articles %}
        <div class="row featurette">
            <div class="col-md-7">
                <h3 class="featurette-heading">{{ article.title }}
                    <a href="{% url 'myblog:show-article' article.id %}">
                        <button type="button" id="loading-example-btn" data-loading-text="Loading..." class="btn btn-primary">Read</button>
                    </a>
                </h3>

                {{ article.text }}
                <!-- Generates 3 points: ... -->
                <!-- </p>&hellip;</p> -->
            </div>
            <div class="col-md-5">
<!--                 <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="Generic placeholder image" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRgpOd6gHameExZyvZDm4mIaXrrNJcEoIa1jjZBL2IJEnoZToPN4A"> -->
                <img class="img-responsive featurette-heading" alt="Generic placeholder image" src={{ article.image }}>
            </div>
        </div>
        <hr class="featurette-divider">{% endfor %}
        </ul>
    {% else %}
        <p>No articles are available</p>
        {{ article }}
    {% endif %}
{% endblock %}
Status API Training Shop Blog About © 2014 GitHub, Inc. Terms Privacy Security Contact 

blog/myblog/templates/myblog/show_article.html
{% extends 'myblog/base.html' %}

{% block go_back %}
<!-- Go Back Button -->
<div class="align-text">

    {% if error_message %}
    <p>
        <strong>{{ error_message }}</strong>
    </p>{% endif %}
    <form action="{url 'myblog:show-article' article.id">
        <img src={{ article.image }} class="article-image">
        <h1>{{ article.title|striptags}}</h1>

        <p>{{ article.text|striptags}}</p>
        <br/>
        <br/>
            <button type="button" class="btn btn-info btn-lg pull-right" id="back">Back</button>
    </form>
    <p>If you want you may leave a comment below:</p>

    <form action='{% url "myblog:show-article" article.id %}' method="post">
        {% csrf_token %}
        <textarea name="comment" rows="4" cols="50" id="commentBodyField" placeholder="Enter your comment..." maxlength="300"></textarea>
        <button class="btn btn-submit" id="send-comment">Send comment</button>
    </form>
    <br>

    <img src="http://d3haopv1cs1fi8.cloudfront.net/img/innhand/facebook-booking-app/facebook-like-button.png" class="like" />
    <form action="." method="post">
        <p id="liked" data-rating="{{ article.rating }}">Rating:
            <span>{{ article.rating }}</span>
        </p>
    </form>
    </div>
  <hr>
{% endblock go_back %}